# Generated by Django 4.2.1 on 2023-11-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCount', models.IntegerField(default=0, max_length=1000)),
            ],
            options={
                'db_table': 'countTable',
            },
        ),
    ]
