# Generated by Django 4.2.1 on 2023-11-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_breakfastcount_dinnercount_lunchcount_snackscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('breakfastTotalCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('dinnerTotalCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('lunchTotalCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='overallTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('TotalCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('snacksTotalCount', models.IntegerField(default=0)),
            ],
        ),
    ]
